---
site_name: MkDocs Tech Docs Template
repo_url: https://github.com/ministryofjustice/mkdocs-tech-docs-template

theme:
  name: material
  custom_dir: 'tech_docs_template/'
  logo: logos/moj.png
  favicon: favicons/moj.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - content.action.view
    # - toc.integrate # uncomment to merge TOC with navigation bar
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition:
      quote: octicons/quote-16
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

edit_uri: edit/main/docs/
plugins:
  - material/search
  - table-reader
  - mknotebooks
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      exclude:
          - README.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://mojdt.slack.com/archives/CBVUV2613
    - icon: fontawesome/solid/paper-plane 
      link: mailto:soumaya.mauthoor@digital.justice.gov.uk
    - icon: fontawesome/brands/github
      link: https://github.com/ministryofjustice/mkdocs-tech-docs-template/discussions

nav:
  - Home:
      - README.md
  - Setup: 
      - setup/README.md
      - Customise: setup/customise.md
      - Contribute: setup/CONTRIBUTE.md
  - Plugins:
      - plugins/README.md
      - Demo Table: plugins/demo_table.md
      - Demo Notebook: plugins/demo_notebook.ipynb
